#!/bin/bash

source ~/.bash/colors.sh

# turns my dev env on or off

if [ "$1" == "on" ]; then
	echo -e "${WHITE}Starting development services"
	echo -e "${GREEN}Starting${LIGHT_GRAY} Apache"
	sudo apachectl start
	echo -e "${GREEN}Starting${LIGHT_GRAY} Redis"
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
	echo -e "${GREEN}Starting${LIGHT_GRAY} MySQL"
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
	echo -e "${GREEN}Starting${LIGHT_GRAY} PostgreSQL"
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
elif [ "$1" == "off" ]; then
	echo -e "${WHITE}Stopping development services"
	echo -e "${RED}Stopping${LIGHT_GRAY} Apache"
	sudo apachectl stop
	echo -e "${RED}Stopping${LIGHT_GRAY} Redis"
	launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
	echo -e "${RED}Stopping${LIGHT_GRAY} MySQL"
	launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
	echo -e "${RED}Stopping${LIGHT_GRAY} PostgreSQL"
	launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
else
	apache_on=$(pgrep httpd)
	if [ -z "$apache_on" ]; then
		echo -e "${LIGHT_GRAY}Development services are ${RED}off"
	else
		echo -e "${LIGHT_GRAY}Development services are ${GREEN}on"
	fi
fi

echo -ne "${RESET}"
