#!/bin/bash

# Switches php versions
#
# Required
# - ./development
# - apache2
# - homebrew php versions
# - ~/.templates/*
# - ~/.bootstrap OR include ~/.custom/phppath.sh

source ~/.bash/colors.sh

new_version="$1"
major_version=$(cut -c1 <<< "$new_version")
homebrew_package="php${new_version}"
old_package=$(which php | grep -Eo 'php[0-9]+')

if [ -z "$new_version" ]; then
	echo -e "${RED}No version selected:${LIGHT_GRAY} php-switch \$VERSION"
	echo -ne "${RESET}"
	exit 1
fi

brew_path=$(brew --prefix "$homebrew_package" 2>/dev/null)

if [ -z "$brew_path" ]; then
	echo -e "${RED}${homebrew_package}${LIGHT_GRAY} not installed"
	echo -ne "${RESET}"
	exit 1
fi

template_file_path=~/.templates/php.conf.template
path_template_file_path=~/.templates/phppath.sh.template

if [ ! -e "$template_file_path" -o ! -e "$path_template_file_path" ]; then
	echo -e "${RED}Template files missing${LIGHT_GRAY}"
	echo -ne "${RESET}"
	exit 1
fi

echo -e "${LIGHT_GRAY}Switching to php version ${GREEN}${new_version}"
echo -ne "${RESET}"

php_path_path=~/.custom/phppath.sh

cp -f "$path_template_file_path" "$php_path_path"
sed -i -e "s/__VERSION__/${homebrew_package}/g" "$php_path_path"

apache_conf_path=/usr/local/etc/apache2/2.4/other/php.conf

sudo cp -f "$template_file_path" "$apache_conf_path"
sudo sed -i -e "s/__VERSION__/${homebrew_package}/g" "$apache_conf_path"
sudo sed -i -e "s/__MAJORVERSION__/${major_version}/g" "$apache_conf_path"
sudo chown root:wheel "$apache_conf_path"
sudo chmod 444 "$apache_conf_path"

brew unlink "${old_package}"
brew unlink "${homebrew_package}" && brew link --overwrite "${homebrew_package}"

development off
development on

echo -e "${GREEN}Done! ${LIGHT_GRAY}Make sure to source ~/.bootstrap to use ${new_version} in this shell"
echo -ne "${RESET}"
